nodeLinker: pnpm

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

npmScopes:
  storipress:
    npmRegistryServer: "https://registry.yarnpkg.com"

yarnPath: .yarn/releases/yarn-4.9.1.cjs
